name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger build on push to main branch

permissions:
  contents: write # Required to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # Next.js static export folder name
          branch: gh-pages # Target branch for deployment
